---
title: "Fit a model using sircovid"
author: "Lilith Whittles"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{model-fitting}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Estimating the marginal likelihood

You will need to specify:

 * the sircovid model: Select your model from the available options found in `inst/odin/`. Or, alternatively, write a new one see <<vignettes/new-model.Rmd>>
 
 *  the data to model: the function `generate_data()` will take the dummy data included in the package and reformat it. The data types should match those specified in the compare function of your sircovid model.
 
* the model parameters: default parameters for each sircovid model can be generated using `generate_parameters()`
which can then be modified

* the observation parameters: these are the parameters that relate the data to the modelled trajectories via the observation distribution specified in the `compare()` function. 

Then call the function `run_particle_filter()` to estimate the marginal log likelihood:

```
  time_steps_per_day <- 4
  data <- generate_data(death_data_file = "covid_cases_2020_4_3.csv",
                        admissions_data_file = "combin_time_series.csv")
  sircovid_model <- modified_hospital_model()
  

  model_params <- generate_parameters(sircovid_model)
  
  obs_params <- list(phi_ICU = 0.95,
                     k_ICU = 2,
                     phi_death = 1789/1651,
                     k_death = 2,
                     exp_noise = 1e6)
  
  log_likelihood <- run_particle_filter(data = data,
                                        sircovid_model = sircovid_model,
                                        model_params = model_params,
                                        obs_params = obs_params,
                                        n_particles = 100, 
                                        return = "ll")
```

## Fit the model using a simple grid search



## Fit the model using pmcmc

### Specify starting conditions

### Specify priors

### Specify a proposal kernel


## Forecasting using the fitted parameters
