---
title: "Add a new model"
author: "John Lees"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{new-model}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Write your new odin model
Write a new odin model and save it as `inst/odin/<model_name>.R`. The easiest way to do this is copy an existing model and modify it. Things to bear in mind for the subsequent steps:

* Have you added any `user` parameters which will need to be passed in?
* Have you renamed any parameters?

### Compile your model
From the root of the package run:
```
odin::odin_package(".")
```
Then reinstall the package, which will actually compile the C code generated by odin:
```
devtools::install(".")
```

## Add a new model object
In `models.R` you'll need to add a new function which initialises your model, along with its helper functions. A `sircovid_model` consists of:

* An `odin_model`, loaded by `load_odin_model("model_name")`.
* A function `generate_beta_func`, which sets a time series of $\beta$ based on a start value. An example is `generate_beta()` defined in `parameters.R`.
* A function `compare_model(model, pars_obs, data)` which compares model output to data and generates a likelihood. An example is `compare_output()` defined in `compare.R`. This function needs to take three arguments, the odin model, parameters used to calculate the likelihood and the data. To pass other arguments to the function first bind them here -- see `hosptial_model()` for an example.
* `progression_groups` are the number of progression groups for each partition which needs these defined (`s_<partition>`). A named list.
* `gammas` rate of progression between each group in `progression_groups` (`gamma_<partition>`). A named list.

The easiest way to set this up is to inherit from the model you copied from, and then overwrite the `odin_model`. For example, if you modified the `hospital_model()`:
```
modified_hospital_model <- function(use_fitted_parameters = TRUE,
                           progression_groups = list(E = 2, asympt = 1, mild = 1, ILI = 1, hosp_D = 2 , hosp_R = 2, ICU_D = 2, ICU_R = 2, triage = 2, stepdown = 2),
                           gammas = list(E = 1/(4.59/2), asympt = 1/2.09, mild = 1/2.09, ILI = 1/4, hosp_D = 2/5, hosp_R = 2/10, ICU_D = 2/5, ICU_R = 2/10, triage = 2, stepdown = 2/5)) {
  model_class <- "sircovid_modified_hospital_model"
  new_model <- hospital_model(use_fitted_parameters = use_fitted_parameters,
                                   progression_groups = progression_groups,
                                   gammas = gammas)
  new_model$odin_model <- load_odin_model("modified_hospital_model")
  
  class(new_model) <- c(model_class, "sircovid_hospital")
  new_model
}
```

Finally, add your progression group names as a new clause to the `partition_names()` function in `models.R`:
```
partition_names <- function(model_name) {
  if (inherits(model_name, "sircovid_basic") || inherits(model_name, "sircovid_hospital")) {
    model_partitions <- names(model_name$progression_groups)
  } else {
    if (model_name == "sircovid_basic") {
      model_partitions <- c("E", "asympt", "mild", "ILI", "hosp", "ICU", "rec")
    } else if (model_name == "sircovid_hospital") {
      model_partitions <- c("E", "asympt", "mild", "ILI", "hosp_D", "hosp_R", "ICU_D", "ICU_R", "triage", "stepdown")
    } else if (model_name == "sircovid_modified_hospital_model") {
      model_partitions <- c("E", "asympt", "mild", "ILI", "hosp_D", "hosp_R", "ICU_D", "ICU_R", "triage", "stepdown")
    } else {
      stop("Unknown model name")
    }
  }
  model_partitions
}
```

By setting the `class` of the model to inherit from the model it is derived from, the parameters will be generated in the same way and everything should work. However, if you have added/modified parameters, a couple of further changes are needed.

### Modifying partitions
If you have changed the partitions you will need to modify `generate_parameters()` to generate initial conditions for these. Add a new clause to the section labelled `Set the initial conditions for each partition` for your model class, and modify values in `parameter_list` by copying a template from an existing model.

### Modifying parameters
If you have removed parameters you will need to set these to `NULL` in the section `Remove parameters unused by odin` to remove warnings.

If you have added parameters you will need to add appropriate code to `generate_parameters()` which creates these and stores them in `parameter_list$<parameter_name>`.

Try to avoid renaming parameters, as this will require doing both of the above steps.

To create conditionals based on your model name use:
```
if (class(sircovid_model)[1] == "sircovid_modified_hospital_model")
```
for statements that should *only* be run for the new model, or:
```
"sircovid_hospital" %in% class(sircovid_model)
```
for statements that should be run for a model or anything that inherits from it.

## Using the new model and adding tests
The best way to get started is to add a new test to `tests/testthat/test-sircovid.R`. Copy the first test `"Can be run on real data"` and change the `sircovid_model`:
```
test_that("Can be run on real data", {
  set.seed(1)
  time_steps_per_day <- 4
  data <- generate_data(death_data_file = "covid_cases_2020_4_3.csv",
                        admissions_data_file = "combin_time_series.csv")
  sircovid_model <- modified_hospital_model()
  
  vary_beta <- sircovid_model$generate_beta_func(0.1)
  model_params <- generate_parameters(sircovid_model,
                                      beta = vary_beta$beta,
                                      beta_times = vary_beta$beta_times,
                                      dt = 1/time_steps_per_day)
  
  results <- run_particle_filter(data = data,
                                 sircovid_model = sircovid_model,
                                 model_params = model_params,
                                 obs_params = list(phi_ICU = 0.95,
                                                   k_ICU = 2,
                                                   phi_death = 1789/1651,
                                                   k_death = 2,
                                                   exp_noise = 1e6),
                                 n_particles = 1000)
```
