steps:
  - label: ":whale::rstats: Build"
    command: docker/build

  - wait

  - label: ":allthethings: Build cuda image"
    command: docker/build_cuda

  - wait

  - label: ":shipit: Push images"
    command: docker/push
