// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// basic.cpp
SEXP dust2_system_basic_alloc(cpp11::list r_pars, cpp11::sexp r_time, cpp11::list r_time_control, cpp11::sexp r_n_particles, cpp11::sexp r_n_groups, cpp11::sexp r_seed, cpp11::sexp r_deterministic, cpp11::sexp r_n_threads);
extern "C" SEXP _sircovid_dust2_system_basic_alloc(SEXP r_pars, SEXP r_time, SEXP r_time_control, SEXP r_n_particles, SEXP r_n_groups, SEXP r_seed, SEXP r_deterministic, SEXP r_n_threads) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_basic_alloc(cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_pars), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_time), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_time_control), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_particles), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_groups), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_seed), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_deterministic), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_threads)));
  END_CPP11
}
// basic.cpp
SEXP dust2_system_basic_run_to_time(cpp11::sexp ptr, cpp11::sexp r_time);
extern "C" SEXP _sircovid_dust2_system_basic_run_to_time(SEXP ptr, SEXP r_time) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_basic_run_to_time(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_time)));
  END_CPP11
}
// basic.cpp
SEXP dust2_system_basic_state(cpp11::sexp ptr, cpp11::sexp r_index_state, cpp11::sexp r_index_particle, cpp11::sexp r_index_group, bool preserve_particle_dimension, bool preserve_group_dimension);
extern "C" SEXP _sircovid_dust2_system_basic_state(SEXP ptr, SEXP r_index_state, SEXP r_index_particle, SEXP r_index_group, SEXP preserve_particle_dimension, SEXP preserve_group_dimension) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_basic_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_state), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_particle), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_group), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_particle_dimension), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_group_dimension)));
  END_CPP11
}
// basic.cpp
SEXP dust2_system_basic_time(cpp11::sexp ptr);
extern "C" SEXP _sircovid_dust2_system_basic_time(SEXP ptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_basic_time(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr)));
  END_CPP11
}
// basic.cpp
SEXP dust2_system_basic_set_state_initial(cpp11::sexp ptr);
extern "C" SEXP _sircovid_dust2_system_basic_set_state_initial(SEXP ptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_basic_set_state_initial(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr)));
  END_CPP11
}
// basic.cpp
SEXP dust2_system_basic_set_state(cpp11::sexp ptr, cpp11::list r_state);
extern "C" SEXP _sircovid_dust2_system_basic_set_state(SEXP ptr, SEXP r_state) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_basic_set_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_state)));
  END_CPP11
}
// basic.cpp
SEXP dust2_system_basic_reorder(cpp11::sexp ptr, cpp11::integers r_index);
extern "C" SEXP _sircovid_dust2_system_basic_reorder(SEXP ptr, SEXP r_index) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_basic_reorder(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(r_index)));
  END_CPP11
}
// basic.cpp
SEXP dust2_system_basic_rng_state(cpp11::sexp ptr);
extern "C" SEXP _sircovid_dust2_system_basic_rng_state(SEXP ptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_basic_rng_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr)));
  END_CPP11
}
// basic.cpp
SEXP dust2_system_basic_set_rng_state(cpp11::sexp ptr, cpp11::sexp r_rng_state);
extern "C" SEXP _sircovid_dust2_system_basic_set_rng_state(SEXP ptr, SEXP r_rng_state) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_basic_set_rng_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_rng_state)));
  END_CPP11
}
// basic.cpp
SEXP dust2_system_basic_set_time(cpp11::sexp ptr, cpp11::sexp r_time);
extern "C" SEXP _sircovid_dust2_system_basic_set_time(SEXP ptr, SEXP r_time) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_basic_set_time(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_time)));
  END_CPP11
}
// basic.cpp
SEXP dust2_system_basic_update_pars(cpp11::sexp ptr, cpp11::list pars);
extern "C" SEXP _sircovid_dust2_system_basic_update_pars(SEXP ptr, SEXP pars) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_basic_update_pars(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(pars)));
  END_CPP11
}
// basic.cpp
SEXP dust2_system_basic_simulate(cpp11::sexp ptr, cpp11::sexp r_times, cpp11::sexp r_index_state, bool preserve_particle_dimension, bool preserve_group_dimension);
extern "C" SEXP _sircovid_dust2_system_basic_simulate(SEXP ptr, SEXP r_times, SEXP r_index_state, SEXP preserve_particle_dimension, SEXP preserve_group_dimension) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_basic_simulate(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_times), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_state), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_particle_dimension), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_group_dimension)));
  END_CPP11
}
// basic.cpp
SEXP dust2_unfilter_basic_alloc(cpp11::list r_pars, cpp11::sexp r_time_start, cpp11::sexp r_time, cpp11::list r_time_control, cpp11::list r_data, cpp11::sexp r_n_particles, cpp11::sexp r_n_groups, cpp11::sexp r_n_threads);
extern "C" SEXP _sircovid_dust2_unfilter_basic_alloc(SEXP r_pars, SEXP r_time_start, SEXP r_time, SEXP r_time_control, SEXP r_data, SEXP r_n_particles, SEXP r_n_groups, SEXP r_n_threads) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_unfilter_basic_alloc(cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_pars), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_time_start), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_time), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_time_control), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_data), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_particles), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_groups), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_threads)));
  END_CPP11
}
// basic.cpp
SEXP dust2_filter_basic_alloc(cpp11::list r_pars, cpp11::sexp r_time_start, cpp11::sexp r_time, cpp11::list r_time_control, cpp11::list r_data, cpp11::sexp r_n_particles, cpp11::sexp r_n_groups, cpp11::sexp r_n_threads, cpp11::sexp r_seed);
extern "C" SEXP _sircovid_dust2_filter_basic_alloc(SEXP r_pars, SEXP r_time_start, SEXP r_time, SEXP r_time_control, SEXP r_data, SEXP r_n_particles, SEXP r_n_groups, SEXP r_n_threads, SEXP r_seed) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_filter_basic_alloc(cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_pars), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_time_start), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_time), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_time_control), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_data), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_particles), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_groups), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_threads), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_seed)));
  END_CPP11
}
// basic.cpp
SEXP dust2_system_basic_compare_data(cpp11::sexp ptr, cpp11::list r_data, bool preserve_particle_dimension, bool preserve_group_dimension);
extern "C" SEXP _sircovid_dust2_system_basic_compare_data(SEXP ptr, SEXP r_data, SEXP preserve_particle_dimension, SEXP preserve_group_dimension) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_basic_compare_data(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_data), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_particle_dimension), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_group_dimension)));
  END_CPP11
}
// basic.cpp
SEXP dust2_unfilter_basic_update_pars(cpp11::sexp ptr, cpp11::list r_pars, cpp11::sexp r_index_group);
extern "C" SEXP _sircovid_dust2_unfilter_basic_update_pars(SEXP ptr, SEXP r_pars, SEXP r_index_group) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_unfilter_basic_update_pars(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_pars), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_group)));
  END_CPP11
}
// basic.cpp
SEXP dust2_unfilter_basic_run(cpp11::sexp ptr, cpp11::sexp r_initial, bool save_trajectories, cpp11::sexp save_snapshots, bool adjoint, cpp11::sexp r_index_state, cpp11::sexp r_index_group, bool preserve_particle_dimension, bool preserve_group_dimension);
extern "C" SEXP _sircovid_dust2_unfilter_basic_run(SEXP ptr, SEXP r_initial, SEXP save_trajectories, SEXP save_snapshots, SEXP adjoint, SEXP r_index_state, SEXP r_index_group, SEXP preserve_particle_dimension, SEXP preserve_group_dimension) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_unfilter_basic_run(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_initial), cpp11::as_cpp<cpp11::decay_t<bool>>(save_trajectories), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(save_snapshots), cpp11::as_cpp<cpp11::decay_t<bool>>(adjoint), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_state), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_group), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_particle_dimension), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_group_dimension)));
  END_CPP11
}
// basic.cpp
SEXP dust2_unfilter_basic_last_trajectories(cpp11::sexp ptr, bool select_random_particle, bool preserve_particle_dimension, bool preserve_group_dimension);
extern "C" SEXP _sircovid_dust2_unfilter_basic_last_trajectories(SEXP ptr, SEXP select_random_particle, SEXP preserve_particle_dimension, SEXP preserve_group_dimension) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_unfilter_basic_last_trajectories(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<bool>>(select_random_particle), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_particle_dimension), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_group_dimension)));
  END_CPP11
}
// basic.cpp
SEXP dust2_unfilter_basic_last_snapshots(cpp11::sexp ptr, bool select_random_particle, bool preserve_particle_dimension, bool preserve_group_dimension);
extern "C" SEXP _sircovid_dust2_unfilter_basic_last_snapshots(SEXP ptr, SEXP select_random_particle, SEXP preserve_particle_dimension, SEXP preserve_group_dimension) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_unfilter_basic_last_snapshots(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<bool>>(select_random_particle), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_particle_dimension), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_group_dimension)));
  END_CPP11
}
// basic.cpp
SEXP dust2_unfilter_basic_last_state(cpp11::sexp ptr, bool select_random_particle, bool preserve_particle_dimension, bool preserve_group_dimension);
extern "C" SEXP _sircovid_dust2_unfilter_basic_last_state(SEXP ptr, SEXP select_random_particle, SEXP preserve_particle_dimension, SEXP preserve_group_dimension) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_unfilter_basic_last_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<bool>>(select_random_particle), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_particle_dimension), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_group_dimension)));
  END_CPP11
}
// basic.cpp
SEXP dust2_filter_basic_update_pars(cpp11::sexp ptr, cpp11::list r_pars, cpp11::sexp r_index_group);
extern "C" SEXP _sircovid_dust2_filter_basic_update_pars(SEXP ptr, SEXP r_pars, SEXP r_index_group) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_filter_basic_update_pars(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_pars), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_group)));
  END_CPP11
}
// basic.cpp
SEXP dust2_filter_basic_run(cpp11::sexp ptr, cpp11::sexp r_initial, bool save_trajectories, cpp11::sexp save_snapshots, bool adjoint, cpp11::sexp index_state, cpp11::sexp index_group, bool preserve_particle_dimension, bool preserve_group_dimension);
extern "C" SEXP _sircovid_dust2_filter_basic_run(SEXP ptr, SEXP r_initial, SEXP save_trajectories, SEXP save_snapshots, SEXP adjoint, SEXP index_state, SEXP index_group, SEXP preserve_particle_dimension, SEXP preserve_group_dimension) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_filter_basic_run(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_initial), cpp11::as_cpp<cpp11::decay_t<bool>>(save_trajectories), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(save_snapshots), cpp11::as_cpp<cpp11::decay_t<bool>>(adjoint), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(index_state), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(index_group), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_particle_dimension), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_group_dimension)));
  END_CPP11
}
// basic.cpp
SEXP dust2_filter_basic_last_trajectories(cpp11::sexp ptr, bool select_random_particle, bool preserve_particle_dimension, bool preserve_group_dimension);
extern "C" SEXP _sircovid_dust2_filter_basic_last_trajectories(SEXP ptr, SEXP select_random_particle, SEXP preserve_particle_dimension, SEXP preserve_group_dimension) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_filter_basic_last_trajectories(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<bool>>(select_random_particle), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_particle_dimension), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_group_dimension)));
  END_CPP11
}
// basic.cpp
SEXP dust2_filter_basic_last_snapshots(cpp11::sexp ptr, bool select_random_particle, bool preserve_particle_dimension, bool preserve_group_dimension);
extern "C" SEXP _sircovid_dust2_filter_basic_last_snapshots(SEXP ptr, SEXP select_random_particle, SEXP preserve_particle_dimension, SEXP preserve_group_dimension) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_filter_basic_last_snapshots(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<bool>>(select_random_particle), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_particle_dimension), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_group_dimension)));
  END_CPP11
}
// basic.cpp
SEXP dust2_filter_basic_last_state(cpp11::sexp ptr, bool select_random_particle, bool preserve_particle_dimension, bool preserve_group_dimension);
extern "C" SEXP _sircovid_dust2_filter_basic_last_state(SEXP ptr, SEXP select_random_particle, SEXP preserve_particle_dimension, SEXP preserve_group_dimension) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_filter_basic_last_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<bool>>(select_random_particle), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_particle_dimension), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_group_dimension)));
  END_CPP11
}
// basic.cpp
SEXP dust2_filter_basic_rng_state(cpp11::sexp ptr);
extern "C" SEXP _sircovid_dust2_filter_basic_rng_state(SEXP ptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_filter_basic_rng_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr)));
  END_CPP11
}
// basic.cpp
SEXP dust2_filter_basic_set_rng_state(cpp11::sexp ptr, cpp11::sexp r_rng_state);
extern "C" SEXP _sircovid_dust2_filter_basic_set_rng_state(SEXP ptr, SEXP r_rng_state) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_filter_basic_set_rng_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_rng_state)));
  END_CPP11
}
// lancelot.cpp
SEXP dust2_system_lancelot_alloc(cpp11::list r_pars, cpp11::sexp r_time, cpp11::list r_time_control, cpp11::sexp r_n_particles, cpp11::sexp r_n_groups, cpp11::sexp r_seed, cpp11::sexp r_deterministic, cpp11::sexp r_n_threads);
extern "C" SEXP _sircovid_dust2_system_lancelot_alloc(SEXP r_pars, SEXP r_time, SEXP r_time_control, SEXP r_n_particles, SEXP r_n_groups, SEXP r_seed, SEXP r_deterministic, SEXP r_n_threads) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_lancelot_alloc(cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_pars), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_time), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_time_control), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_particles), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_groups), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_seed), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_deterministic), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_threads)));
  END_CPP11
}
// lancelot.cpp
SEXP dust2_system_lancelot_run_to_time(cpp11::sexp ptr, cpp11::sexp r_time);
extern "C" SEXP _sircovid_dust2_system_lancelot_run_to_time(SEXP ptr, SEXP r_time) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_lancelot_run_to_time(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_time)));
  END_CPP11
}
// lancelot.cpp
SEXP dust2_system_lancelot_state(cpp11::sexp ptr, cpp11::sexp r_index_state, cpp11::sexp r_index_particle, cpp11::sexp r_index_group, bool preserve_particle_dimension, bool preserve_group_dimension);
extern "C" SEXP _sircovid_dust2_system_lancelot_state(SEXP ptr, SEXP r_index_state, SEXP r_index_particle, SEXP r_index_group, SEXP preserve_particle_dimension, SEXP preserve_group_dimension) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_lancelot_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_state), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_particle), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_group), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_particle_dimension), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_group_dimension)));
  END_CPP11
}
// lancelot.cpp
SEXP dust2_system_lancelot_time(cpp11::sexp ptr);
extern "C" SEXP _sircovid_dust2_system_lancelot_time(SEXP ptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_lancelot_time(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr)));
  END_CPP11
}
// lancelot.cpp
SEXP dust2_system_lancelot_set_state_initial(cpp11::sexp ptr);
extern "C" SEXP _sircovid_dust2_system_lancelot_set_state_initial(SEXP ptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_lancelot_set_state_initial(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr)));
  END_CPP11
}
// lancelot.cpp
SEXP dust2_system_lancelot_set_state(cpp11::sexp ptr, cpp11::list r_state);
extern "C" SEXP _sircovid_dust2_system_lancelot_set_state(SEXP ptr, SEXP r_state) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_lancelot_set_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_state)));
  END_CPP11
}
// lancelot.cpp
SEXP dust2_system_lancelot_reorder(cpp11::sexp ptr, cpp11::integers r_index);
extern "C" SEXP _sircovid_dust2_system_lancelot_reorder(SEXP ptr, SEXP r_index) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_lancelot_reorder(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(r_index)));
  END_CPP11
}
// lancelot.cpp
SEXP dust2_system_lancelot_rng_state(cpp11::sexp ptr);
extern "C" SEXP _sircovid_dust2_system_lancelot_rng_state(SEXP ptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_lancelot_rng_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr)));
  END_CPP11
}
// lancelot.cpp
SEXP dust2_system_lancelot_set_rng_state(cpp11::sexp ptr, cpp11::sexp r_rng_state);
extern "C" SEXP _sircovid_dust2_system_lancelot_set_rng_state(SEXP ptr, SEXP r_rng_state) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_lancelot_set_rng_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_rng_state)));
  END_CPP11
}
// lancelot.cpp
SEXP dust2_system_lancelot_set_time(cpp11::sexp ptr, cpp11::sexp r_time);
extern "C" SEXP _sircovid_dust2_system_lancelot_set_time(SEXP ptr, SEXP r_time) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_lancelot_set_time(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_time)));
  END_CPP11
}
// lancelot.cpp
SEXP dust2_system_lancelot_update_pars(cpp11::sexp ptr, cpp11::list pars);
extern "C" SEXP _sircovid_dust2_system_lancelot_update_pars(SEXP ptr, SEXP pars) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_lancelot_update_pars(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(pars)));
  END_CPP11
}
// lancelot.cpp
SEXP dust2_system_lancelot_simulate(cpp11::sexp ptr, cpp11::sexp r_times, cpp11::sexp r_index_state, bool preserve_particle_dimension, bool preserve_group_dimension);
extern "C" SEXP _sircovid_dust2_system_lancelot_simulate(SEXP ptr, SEXP r_times, SEXP r_index_state, SEXP preserve_particle_dimension, SEXP preserve_group_dimension) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_lancelot_simulate(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_times), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_state), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_particle_dimension), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_group_dimension)));
  END_CPP11
}
// lancelot.cpp
SEXP dust2_unfilter_lancelot_alloc(cpp11::list r_pars, cpp11::sexp r_time_start, cpp11::sexp r_time, cpp11::list r_time_control, cpp11::list r_data, cpp11::sexp r_n_particles, cpp11::sexp r_n_groups, cpp11::sexp r_n_threads);
extern "C" SEXP _sircovid_dust2_unfilter_lancelot_alloc(SEXP r_pars, SEXP r_time_start, SEXP r_time, SEXP r_time_control, SEXP r_data, SEXP r_n_particles, SEXP r_n_groups, SEXP r_n_threads) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_unfilter_lancelot_alloc(cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_pars), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_time_start), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_time), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_time_control), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_data), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_particles), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_groups), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_threads)));
  END_CPP11
}
// lancelot.cpp
SEXP dust2_filter_lancelot_alloc(cpp11::list r_pars, cpp11::sexp r_time_start, cpp11::sexp r_time, cpp11::list r_time_control, cpp11::list r_data, cpp11::sexp r_n_particles, cpp11::sexp r_n_groups, cpp11::sexp r_n_threads, cpp11::sexp r_seed);
extern "C" SEXP _sircovid_dust2_filter_lancelot_alloc(SEXP r_pars, SEXP r_time_start, SEXP r_time, SEXP r_time_control, SEXP r_data, SEXP r_n_particles, SEXP r_n_groups, SEXP r_n_threads, SEXP r_seed) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_filter_lancelot_alloc(cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_pars), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_time_start), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_time), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_time_control), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_data), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_particles), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_groups), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_threads), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_seed)));
  END_CPP11
}
// lancelot.cpp
SEXP dust2_system_lancelot_compare_data(cpp11::sexp ptr, cpp11::list r_data, bool preserve_particle_dimension, bool preserve_group_dimension);
extern "C" SEXP _sircovid_dust2_system_lancelot_compare_data(SEXP ptr, SEXP r_data, SEXP preserve_particle_dimension, SEXP preserve_group_dimension) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_lancelot_compare_data(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_data), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_particle_dimension), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_group_dimension)));
  END_CPP11
}
// lancelot.cpp
SEXP dust2_unfilter_lancelot_update_pars(cpp11::sexp ptr, cpp11::list r_pars, cpp11::sexp r_index_group);
extern "C" SEXP _sircovid_dust2_unfilter_lancelot_update_pars(SEXP ptr, SEXP r_pars, SEXP r_index_group) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_unfilter_lancelot_update_pars(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_pars), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_group)));
  END_CPP11
}
// lancelot.cpp
SEXP dust2_unfilter_lancelot_run(cpp11::sexp ptr, cpp11::sexp r_initial, bool save_trajectories, cpp11::sexp save_snapshots, bool adjoint, cpp11::sexp r_index_state, cpp11::sexp r_index_group, bool preserve_particle_dimension, bool preserve_group_dimension);
extern "C" SEXP _sircovid_dust2_unfilter_lancelot_run(SEXP ptr, SEXP r_initial, SEXP save_trajectories, SEXP save_snapshots, SEXP adjoint, SEXP r_index_state, SEXP r_index_group, SEXP preserve_particle_dimension, SEXP preserve_group_dimension) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_unfilter_lancelot_run(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_initial), cpp11::as_cpp<cpp11::decay_t<bool>>(save_trajectories), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(save_snapshots), cpp11::as_cpp<cpp11::decay_t<bool>>(adjoint), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_state), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_group), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_particle_dimension), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_group_dimension)));
  END_CPP11
}
// lancelot.cpp
SEXP dust2_unfilter_lancelot_last_trajectories(cpp11::sexp ptr, bool select_random_particle, bool preserve_particle_dimension, bool preserve_group_dimension);
extern "C" SEXP _sircovid_dust2_unfilter_lancelot_last_trajectories(SEXP ptr, SEXP select_random_particle, SEXP preserve_particle_dimension, SEXP preserve_group_dimension) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_unfilter_lancelot_last_trajectories(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<bool>>(select_random_particle), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_particle_dimension), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_group_dimension)));
  END_CPP11
}
// lancelot.cpp
SEXP dust2_unfilter_lancelot_last_snapshots(cpp11::sexp ptr, bool select_random_particle, bool preserve_particle_dimension, bool preserve_group_dimension);
extern "C" SEXP _sircovid_dust2_unfilter_lancelot_last_snapshots(SEXP ptr, SEXP select_random_particle, SEXP preserve_particle_dimension, SEXP preserve_group_dimension) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_unfilter_lancelot_last_snapshots(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<bool>>(select_random_particle), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_particle_dimension), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_group_dimension)));
  END_CPP11
}
// lancelot.cpp
SEXP dust2_unfilter_lancelot_last_state(cpp11::sexp ptr, bool select_random_particle, bool preserve_particle_dimension, bool preserve_group_dimension);
extern "C" SEXP _sircovid_dust2_unfilter_lancelot_last_state(SEXP ptr, SEXP select_random_particle, SEXP preserve_particle_dimension, SEXP preserve_group_dimension) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_unfilter_lancelot_last_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<bool>>(select_random_particle), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_particle_dimension), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_group_dimension)));
  END_CPP11
}
// lancelot.cpp
SEXP dust2_filter_lancelot_update_pars(cpp11::sexp ptr, cpp11::list r_pars, cpp11::sexp r_index_group);
extern "C" SEXP _sircovid_dust2_filter_lancelot_update_pars(SEXP ptr, SEXP r_pars, SEXP r_index_group) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_filter_lancelot_update_pars(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_pars), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_group)));
  END_CPP11
}
// lancelot.cpp
SEXP dust2_filter_lancelot_run(cpp11::sexp ptr, cpp11::sexp r_initial, bool save_trajectories, cpp11::sexp save_snapshots, bool adjoint, cpp11::sexp index_state, cpp11::sexp index_group, bool preserve_particle_dimension, bool preserve_group_dimension);
extern "C" SEXP _sircovid_dust2_filter_lancelot_run(SEXP ptr, SEXP r_initial, SEXP save_trajectories, SEXP save_snapshots, SEXP adjoint, SEXP index_state, SEXP index_group, SEXP preserve_particle_dimension, SEXP preserve_group_dimension) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_filter_lancelot_run(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_initial), cpp11::as_cpp<cpp11::decay_t<bool>>(save_trajectories), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(save_snapshots), cpp11::as_cpp<cpp11::decay_t<bool>>(adjoint), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(index_state), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(index_group), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_particle_dimension), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_group_dimension)));
  END_CPP11
}
// lancelot.cpp
SEXP dust2_filter_lancelot_last_trajectories(cpp11::sexp ptr, bool select_random_particle, bool preserve_particle_dimension, bool preserve_group_dimension);
extern "C" SEXP _sircovid_dust2_filter_lancelot_last_trajectories(SEXP ptr, SEXP select_random_particle, SEXP preserve_particle_dimension, SEXP preserve_group_dimension) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_filter_lancelot_last_trajectories(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<bool>>(select_random_particle), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_particle_dimension), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_group_dimension)));
  END_CPP11
}
// lancelot.cpp
SEXP dust2_filter_lancelot_last_snapshots(cpp11::sexp ptr, bool select_random_particle, bool preserve_particle_dimension, bool preserve_group_dimension);
extern "C" SEXP _sircovid_dust2_filter_lancelot_last_snapshots(SEXP ptr, SEXP select_random_particle, SEXP preserve_particle_dimension, SEXP preserve_group_dimension) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_filter_lancelot_last_snapshots(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<bool>>(select_random_particle), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_particle_dimension), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_group_dimension)));
  END_CPP11
}
// lancelot.cpp
SEXP dust2_filter_lancelot_last_state(cpp11::sexp ptr, bool select_random_particle, bool preserve_particle_dimension, bool preserve_group_dimension);
extern "C" SEXP _sircovid_dust2_filter_lancelot_last_state(SEXP ptr, SEXP select_random_particle, SEXP preserve_particle_dimension, SEXP preserve_group_dimension) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_filter_lancelot_last_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<bool>>(select_random_particle), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_particle_dimension), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_group_dimension)));
  END_CPP11
}
// lancelot.cpp
SEXP dust2_filter_lancelot_rng_state(cpp11::sexp ptr);
extern "C" SEXP _sircovid_dust2_filter_lancelot_rng_state(SEXP ptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_filter_lancelot_rng_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr)));
  END_CPP11
}
// lancelot.cpp
SEXP dust2_filter_lancelot_set_rng_state(cpp11::sexp ptr, cpp11::sexp r_rng_state);
extern "C" SEXP _sircovid_dust2_filter_lancelot_set_rng_state(SEXP ptr, SEXP r_rng_state) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_filter_lancelot_set_rng_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_rng_state)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_sircovid_dust2_filter_basic_alloc",                  (DL_FUNC) &_sircovid_dust2_filter_basic_alloc,                  9},
    {"_sircovid_dust2_filter_basic_last_snapshots",         (DL_FUNC) &_sircovid_dust2_filter_basic_last_snapshots,         4},
    {"_sircovid_dust2_filter_basic_last_state",             (DL_FUNC) &_sircovid_dust2_filter_basic_last_state,             4},
    {"_sircovid_dust2_filter_basic_last_trajectories",      (DL_FUNC) &_sircovid_dust2_filter_basic_last_trajectories,      4},
    {"_sircovid_dust2_filter_basic_rng_state",              (DL_FUNC) &_sircovid_dust2_filter_basic_rng_state,              1},
    {"_sircovid_dust2_filter_basic_run",                    (DL_FUNC) &_sircovid_dust2_filter_basic_run,                    9},
    {"_sircovid_dust2_filter_basic_set_rng_state",          (DL_FUNC) &_sircovid_dust2_filter_basic_set_rng_state,          2},
    {"_sircovid_dust2_filter_basic_update_pars",            (DL_FUNC) &_sircovid_dust2_filter_basic_update_pars,            3},
    {"_sircovid_dust2_filter_lancelot_alloc",               (DL_FUNC) &_sircovid_dust2_filter_lancelot_alloc,               9},
    {"_sircovid_dust2_filter_lancelot_last_snapshots",      (DL_FUNC) &_sircovid_dust2_filter_lancelot_last_snapshots,      4},
    {"_sircovid_dust2_filter_lancelot_last_state",          (DL_FUNC) &_sircovid_dust2_filter_lancelot_last_state,          4},
    {"_sircovid_dust2_filter_lancelot_last_trajectories",   (DL_FUNC) &_sircovid_dust2_filter_lancelot_last_trajectories,   4},
    {"_sircovid_dust2_filter_lancelot_rng_state",           (DL_FUNC) &_sircovid_dust2_filter_lancelot_rng_state,           1},
    {"_sircovid_dust2_filter_lancelot_run",                 (DL_FUNC) &_sircovid_dust2_filter_lancelot_run,                 9},
    {"_sircovid_dust2_filter_lancelot_set_rng_state",       (DL_FUNC) &_sircovid_dust2_filter_lancelot_set_rng_state,       2},
    {"_sircovid_dust2_filter_lancelot_update_pars",         (DL_FUNC) &_sircovid_dust2_filter_lancelot_update_pars,         3},
    {"_sircovid_dust2_system_basic_alloc",                  (DL_FUNC) &_sircovid_dust2_system_basic_alloc,                  8},
    {"_sircovid_dust2_system_basic_compare_data",           (DL_FUNC) &_sircovid_dust2_system_basic_compare_data,           4},
    {"_sircovid_dust2_system_basic_reorder",                (DL_FUNC) &_sircovid_dust2_system_basic_reorder,                2},
    {"_sircovid_dust2_system_basic_rng_state",              (DL_FUNC) &_sircovid_dust2_system_basic_rng_state,              1},
    {"_sircovid_dust2_system_basic_run_to_time",            (DL_FUNC) &_sircovid_dust2_system_basic_run_to_time,            2},
    {"_sircovid_dust2_system_basic_set_rng_state",          (DL_FUNC) &_sircovid_dust2_system_basic_set_rng_state,          2},
    {"_sircovid_dust2_system_basic_set_state",              (DL_FUNC) &_sircovid_dust2_system_basic_set_state,              2},
    {"_sircovid_dust2_system_basic_set_state_initial",      (DL_FUNC) &_sircovid_dust2_system_basic_set_state_initial,      1},
    {"_sircovid_dust2_system_basic_set_time",               (DL_FUNC) &_sircovid_dust2_system_basic_set_time,               2},
    {"_sircovid_dust2_system_basic_simulate",               (DL_FUNC) &_sircovid_dust2_system_basic_simulate,               5},
    {"_sircovid_dust2_system_basic_state",                  (DL_FUNC) &_sircovid_dust2_system_basic_state,                  6},
    {"_sircovid_dust2_system_basic_time",                   (DL_FUNC) &_sircovid_dust2_system_basic_time,                   1},
    {"_sircovid_dust2_system_basic_update_pars",            (DL_FUNC) &_sircovid_dust2_system_basic_update_pars,            2},
    {"_sircovid_dust2_system_lancelot_alloc",               (DL_FUNC) &_sircovid_dust2_system_lancelot_alloc,               8},
    {"_sircovid_dust2_system_lancelot_compare_data",        (DL_FUNC) &_sircovid_dust2_system_lancelot_compare_data,        4},
    {"_sircovid_dust2_system_lancelot_reorder",             (DL_FUNC) &_sircovid_dust2_system_lancelot_reorder,             2},
    {"_sircovid_dust2_system_lancelot_rng_state",           (DL_FUNC) &_sircovid_dust2_system_lancelot_rng_state,           1},
    {"_sircovid_dust2_system_lancelot_run_to_time",         (DL_FUNC) &_sircovid_dust2_system_lancelot_run_to_time,         2},
    {"_sircovid_dust2_system_lancelot_set_rng_state",       (DL_FUNC) &_sircovid_dust2_system_lancelot_set_rng_state,       2},
    {"_sircovid_dust2_system_lancelot_set_state",           (DL_FUNC) &_sircovid_dust2_system_lancelot_set_state,           2},
    {"_sircovid_dust2_system_lancelot_set_state_initial",   (DL_FUNC) &_sircovid_dust2_system_lancelot_set_state_initial,   1},
    {"_sircovid_dust2_system_lancelot_set_time",            (DL_FUNC) &_sircovid_dust2_system_lancelot_set_time,            2},
    {"_sircovid_dust2_system_lancelot_simulate",            (DL_FUNC) &_sircovid_dust2_system_lancelot_simulate,            5},
    {"_sircovid_dust2_system_lancelot_state",               (DL_FUNC) &_sircovid_dust2_system_lancelot_state,               6},
    {"_sircovid_dust2_system_lancelot_time",                (DL_FUNC) &_sircovid_dust2_system_lancelot_time,                1},
    {"_sircovid_dust2_system_lancelot_update_pars",         (DL_FUNC) &_sircovid_dust2_system_lancelot_update_pars,         2},
    {"_sircovid_dust2_unfilter_basic_alloc",                (DL_FUNC) &_sircovid_dust2_unfilter_basic_alloc,                8},
    {"_sircovid_dust2_unfilter_basic_last_snapshots",       (DL_FUNC) &_sircovid_dust2_unfilter_basic_last_snapshots,       4},
    {"_sircovid_dust2_unfilter_basic_last_state",           (DL_FUNC) &_sircovid_dust2_unfilter_basic_last_state,           4},
    {"_sircovid_dust2_unfilter_basic_last_trajectories",    (DL_FUNC) &_sircovid_dust2_unfilter_basic_last_trajectories,    4},
    {"_sircovid_dust2_unfilter_basic_run",                  (DL_FUNC) &_sircovid_dust2_unfilter_basic_run,                  9},
    {"_sircovid_dust2_unfilter_basic_update_pars",          (DL_FUNC) &_sircovid_dust2_unfilter_basic_update_pars,          3},
    {"_sircovid_dust2_unfilter_lancelot_alloc",             (DL_FUNC) &_sircovid_dust2_unfilter_lancelot_alloc,             8},
    {"_sircovid_dust2_unfilter_lancelot_last_snapshots",    (DL_FUNC) &_sircovid_dust2_unfilter_lancelot_last_snapshots,    4},
    {"_sircovid_dust2_unfilter_lancelot_last_state",        (DL_FUNC) &_sircovid_dust2_unfilter_lancelot_last_state,        4},
    {"_sircovid_dust2_unfilter_lancelot_last_trajectories", (DL_FUNC) &_sircovid_dust2_unfilter_lancelot_last_trajectories, 4},
    {"_sircovid_dust2_unfilter_lancelot_run",               (DL_FUNC) &_sircovid_dust2_unfilter_lancelot_run,               9},
    {"_sircovid_dust2_unfilter_lancelot_update_pars",       (DL_FUNC) &_sircovid_dust2_unfilter_lancelot_update_pars,       3},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_sircovid(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
