# Generated by cpp11: do not edit by hand

dust_carehomes_alloc <- function(r_data, step, n_particles, n_threads, seed) {
  .Call("_sircovid2_dust_carehomes_alloc", r_data, step, n_particles, n_threads, seed)
}

dust_carehomes_run <- function(ptr, step_end) {
  .Call("_sircovid2_dust_carehomes_run", ptr, step_end)
}

dust_carehomes_set_index <- function(ptr, r_index) {
  .Call("_sircovid2_dust_carehomes_set_index", ptr, r_index)
}

dust_carehomes_set_state <- function(ptr, r_state, r_step) {
  .Call("_sircovid2_dust_carehomes_set_state", ptr, r_state, r_step)
}

dust_carehomes_reset <- function(ptr, r_data, step) {
  .Call("_sircovid2_dust_carehomes_reset", ptr, r_data, step)
}

dust_carehomes_state <- function(ptr, r_index) {
  .Call("_sircovid2_dust_carehomes_state", ptr, r_index)
}

dust_carehomes_step <- function(ptr) {
  .Call("_sircovid2_dust_carehomes_step", ptr)
}

dust_carehomes_reorder <- function(ptr, r_index) {
  invisible(.Call("_sircovid2_dust_carehomes_reorder", ptr, r_index))
}

dust_carehomes_rng_state <- function(ptr) {
  .Call("_sircovid2_dust_carehomes_rng_state", ptr)
}
