# Generated by cpp11: do not edit by hand

dust_basic_capabilities <- function() {
  .Call(`_sircovid_dust_basic_capabilities`)
}

dust_basic_gpu_info <- function() {
  .Call(`_sircovid_dust_basic_gpu_info`)
}

dust_cpu_basic_alloc <- function(r_pars, pars_multi, step, r_n_particles, n_threads, r_seed, deterministic, gpu_config) {
  .Call(`_sircovid_dust_cpu_basic_alloc`, r_pars, pars_multi, step, r_n_particles, n_threads, r_seed, deterministic, gpu_config)
}

dust_cpu_basic_run <- function(ptr, step_end) {
  .Call(`_sircovid_dust_cpu_basic_run`, ptr, step_end)
}

dust_cpu_basic_simulate <- function(ptr, step_end) {
  .Call(`_sircovid_dust_cpu_basic_simulate`, ptr, step_end)
}

dust_cpu_basic_set_index <- function(ptr, r_index) {
  .Call(`_sircovid_dust_cpu_basic_set_index`, ptr, r_index)
}

dust_cpu_basic_update_state <- function(ptr, r_pars, r_state, r_step, r_set_initial_state) {
  .Call(`_sircovid_dust_cpu_basic_update_state`, ptr, r_pars, r_state, r_step, r_set_initial_state)
}

dust_cpu_basic_state <- function(ptr, r_index) {
  .Call(`_sircovid_dust_cpu_basic_state`, ptr, r_index)
}

dust_cpu_basic_step <- function(ptr) {
  .Call(`_sircovid_dust_cpu_basic_step`, ptr)
}

dust_cpu_basic_reorder <- function(ptr, r_index) {
  invisible(.Call(`_sircovid_dust_cpu_basic_reorder`, ptr, r_index))
}

dust_cpu_basic_resample <- function(ptr, r_weights) {
  .Call(`_sircovid_dust_cpu_basic_resample`, ptr, r_weights)
}

dust_cpu_basic_rng_state <- function(ptr, first_only, last_only) {
  .Call(`_sircovid_dust_cpu_basic_rng_state`, ptr, first_only, last_only)
}

dust_cpu_basic_set_rng_state <- function(ptr, rng_state) {
  .Call(`_sircovid_dust_cpu_basic_set_rng_state`, ptr, rng_state)
}

dust_cpu_basic_set_data <- function(ptr, data) {
  .Call(`_sircovid_dust_cpu_basic_set_data`, ptr, data)
}

dust_cpu_basic_compare_data <- function(ptr) {
  .Call(`_sircovid_dust_cpu_basic_compare_data`, ptr)
}

dust_cpu_basic_filter <- function(ptr, save_trajectories, step_snapshot) {
  .Call(`_sircovid_dust_cpu_basic_filter`, ptr, save_trajectories, step_snapshot)
}

dust_cpu_basic_set_n_threads <- function(ptr, n_threads) {
  invisible(.Call(`_sircovid_dust_cpu_basic_set_n_threads`, ptr, n_threads))
}

dust_cpu_basic_n_state <- function(ptr) {
  .Call(`_sircovid_dust_cpu_basic_n_state`, ptr)
}

dust_carehomes_capabilities <- function() {
  .Call(`_sircovid_dust_carehomes_capabilities`)
}

dust_carehomes_gpu_info <- function() {
  .Call(`_sircovid_dust_carehomes_gpu_info`)
}

dust_cpu_carehomes_alloc <- function(r_pars, pars_multi, step, r_n_particles, n_threads, r_seed, deterministic, gpu_config) {
  .Call(`_sircovid_dust_cpu_carehomes_alloc`, r_pars, pars_multi, step, r_n_particles, n_threads, r_seed, deterministic, gpu_config)
}

dust_cpu_carehomes_run <- function(ptr, step_end) {
  .Call(`_sircovid_dust_cpu_carehomes_run`, ptr, step_end)
}

dust_cpu_carehomes_simulate <- function(ptr, step_end) {
  .Call(`_sircovid_dust_cpu_carehomes_simulate`, ptr, step_end)
}

dust_cpu_carehomes_set_index <- function(ptr, r_index) {
  .Call(`_sircovid_dust_cpu_carehomes_set_index`, ptr, r_index)
}

dust_cpu_carehomes_update_state <- function(ptr, r_pars, r_state, r_step, r_set_initial_state) {
  .Call(`_sircovid_dust_cpu_carehomes_update_state`, ptr, r_pars, r_state, r_step, r_set_initial_state)
}

dust_cpu_carehomes_state <- function(ptr, r_index) {
  .Call(`_sircovid_dust_cpu_carehomes_state`, ptr, r_index)
}

dust_cpu_carehomes_step <- function(ptr) {
  .Call(`_sircovid_dust_cpu_carehomes_step`, ptr)
}

dust_cpu_carehomes_reorder <- function(ptr, r_index) {
  invisible(.Call(`_sircovid_dust_cpu_carehomes_reorder`, ptr, r_index))
}

dust_cpu_carehomes_resample <- function(ptr, r_weights) {
  .Call(`_sircovid_dust_cpu_carehomes_resample`, ptr, r_weights)
}

dust_cpu_carehomes_rng_state <- function(ptr, first_only, last_only) {
  .Call(`_sircovid_dust_cpu_carehomes_rng_state`, ptr, first_only, last_only)
}

dust_cpu_carehomes_set_rng_state <- function(ptr, rng_state) {
  .Call(`_sircovid_dust_cpu_carehomes_set_rng_state`, ptr, rng_state)
}

dust_cpu_carehomes_set_data <- function(ptr, data) {
  .Call(`_sircovid_dust_cpu_carehomes_set_data`, ptr, data)
}

dust_cpu_carehomes_compare_data <- function(ptr) {
  .Call(`_sircovid_dust_cpu_carehomes_compare_data`, ptr)
}

dust_cpu_carehomes_filter <- function(ptr, save_trajectories, step_snapshot) {
  .Call(`_sircovid_dust_cpu_carehomes_filter`, ptr, save_trajectories, step_snapshot)
}

dust_cpu_carehomes_set_n_threads <- function(ptr, n_threads) {
  invisible(.Call(`_sircovid_dust_cpu_carehomes_set_n_threads`, ptr, n_threads))
}

dust_cpu_carehomes_n_state <- function(ptr) {
  .Call(`_sircovid_dust_cpu_carehomes_n_state`, ptr)
}

dust_lancelot_capabilities <- function() {
  .Call(`_sircovid_dust_lancelot_capabilities`)
}

dust_lancelot_gpu_info <- function() {
  .Call(`_sircovid_dust_lancelot_gpu_info`)
}

dust_cpu_lancelot_alloc <- function(r_pars, pars_multi, step, r_n_particles, n_threads, r_seed, deterministic, gpu_config) {
  .Call(`_sircovid_dust_cpu_lancelot_alloc`, r_pars, pars_multi, step, r_n_particles, n_threads, r_seed, deterministic, gpu_config)
}

dust_cpu_lancelot_run <- function(ptr, step_end) {
  .Call(`_sircovid_dust_cpu_lancelot_run`, ptr, step_end)
}

dust_cpu_lancelot_simulate <- function(ptr, step_end) {
  .Call(`_sircovid_dust_cpu_lancelot_simulate`, ptr, step_end)
}

dust_cpu_lancelot_set_index <- function(ptr, r_index) {
  .Call(`_sircovid_dust_cpu_lancelot_set_index`, ptr, r_index)
}

dust_cpu_lancelot_update_state <- function(ptr, r_pars, r_state, r_step, r_set_initial_state) {
  .Call(`_sircovid_dust_cpu_lancelot_update_state`, ptr, r_pars, r_state, r_step, r_set_initial_state)
}

dust_cpu_lancelot_state <- function(ptr, r_index) {
  .Call(`_sircovid_dust_cpu_lancelot_state`, ptr, r_index)
}

dust_cpu_lancelot_step <- function(ptr) {
  .Call(`_sircovid_dust_cpu_lancelot_step`, ptr)
}

dust_cpu_lancelot_reorder <- function(ptr, r_index) {
  invisible(.Call(`_sircovid_dust_cpu_lancelot_reorder`, ptr, r_index))
}

dust_cpu_lancelot_resample <- function(ptr, r_weights) {
  .Call(`_sircovid_dust_cpu_lancelot_resample`, ptr, r_weights)
}

dust_cpu_lancelot_rng_state <- function(ptr, first_only, last_only) {
  .Call(`_sircovid_dust_cpu_lancelot_rng_state`, ptr, first_only, last_only)
}

dust_cpu_lancelot_set_rng_state <- function(ptr, rng_state) {
  .Call(`_sircovid_dust_cpu_lancelot_set_rng_state`, ptr, rng_state)
}

dust_cpu_lancelot_set_data <- function(ptr, data) {
  .Call(`_sircovid_dust_cpu_lancelot_set_data`, ptr, data)
}

dust_cpu_lancelot_compare_data <- function(ptr) {
  .Call(`_sircovid_dust_cpu_lancelot_compare_data`, ptr)
}

dust_cpu_lancelot_filter <- function(ptr, save_trajectories, step_snapshot) {
  .Call(`_sircovid_dust_cpu_lancelot_filter`, ptr, save_trajectories, step_snapshot)
}

dust_cpu_lancelot_set_n_threads <- function(ptr, n_threads) {
  invisible(.Call(`_sircovid_dust_cpu_lancelot_set_n_threads`, ptr, n_threads))
}

dust_cpu_lancelot_n_state <- function(ptr) {
  .Call(`_sircovid_dust_cpu_lancelot_n_state`, ptr)
}
