## Generated by dust (version 0.2.4) - do not edit
basic <- R6::R6Class(
  "dust",
  cloneable = FALSE,

  private = list(
    data = NULL,
    ptr = NULL
  ),

  public = list(
    initialize = function(data, step, n_particles, n_threads = 1L,
                          seed = 1L) {
      res <- dust_basic_alloc(data, step, n_particles,
                        n_threads, seed)
      private$ptr <- res[[1L]]
      private$data <- res[[2L]]
    },

    name = function() {
      "basic"
    },

    run = function(step_end) {
      dust_basic_run(private$ptr, step_end)
    },

    set_index = function(index) {
      dust_basic_set_index(private$ptr, index)
    },

    set_state = function(state, step = NULL) {
      dust_basic_set_state(private$ptr, state, step)
    },

    reset = function(data, step) {
      private$data <- dust_basic_reset(private$ptr, data, step)
      invisible()
    },

    state = function(index = NULL) {
      dust_basic_state(private$ptr, index)
    },

    step = function() {
      dust_basic_step(private$ptr)
    },

    reorder = function(index) {
      dust_basic_reorder(private$ptr, as.integer(index))
      invisible()
    },

    info = function() {
      private$data
    },

    rng_state = function() {
      dust_basic_rng_state(private$ptr)
    }
  ))
carehomes <- R6::R6Class(
  "dust",
  cloneable = FALSE,

  private = list(
    data = NULL,
    ptr = NULL
  ),

  public = list(
    initialize = function(data, step, n_particles, n_threads = 1L,
                          seed = 1L) {
      res <- dust_carehomes_alloc(data, step, n_particles,
                        n_threads, seed)
      private$ptr <- res[[1L]]
      private$data <- res[[2L]]
    },

    name = function() {
      "carehomes"
    },

    run = function(step_end) {
      dust_carehomes_run(private$ptr, step_end)
    },

    set_index = function(index) {
      dust_carehomes_set_index(private$ptr, index)
    },

    set_state = function(state, step = NULL) {
      dust_carehomes_set_state(private$ptr, state, step)
    },

    reset = function(data, step) {
      private$data <- dust_carehomes_reset(private$ptr, data, step)
      invisible()
    },

    state = function(index = NULL) {
      dust_carehomes_state(private$ptr, index)
    },

    step = function() {
      dust_carehomes_step(private$ptr)
    },

    reorder = function(index) {
      dust_carehomes_reorder(private$ptr, as.integer(index))
      invisible()
    },

    info = function() {
      private$data
    },

    rng_state = function() {
      dust_carehomes_rng_state(private$ptr)
    }
  ))
## Generated by odin.dust (version 0.0.6) - do not edit
basic$set("public", "index", function() {
    n <- vapply(self$info(), prod, numeric(1))
    Map(seq.int, to = cumsum(n), by = 1L, length.out = n)
})
carehomes$set("public", "index", function() {
    n <- vapply(self$info(), prod, numeric(1))
    Map(seq.int, to = cumsum(n), by = 1L, length.out = n)
})
