##' Generate data for fitting the particle filter from reports of
##' deaths and admissions
##' 
##' @title Generate data
##' 
##' @param death_data_file CSV file containing COVID-19 cases, from
##'   the ECDC website 
##' 
##' @param admissions_data_file Admission totals, from ncov-outputs
##' 
##' @param itu_colname Name of the column in the time series file
##'   to be used for fitting ITU cases
##' 
##' @param itu_ignore_dates List of dates to discard from the
##'   data due to error or otherwise
##'   
##' @param first_data_date Date to start data fit from
##' 
##' @param country_name Country name in case reports
##' 
##' @param death_file_day_shift Number of days to subtract from
##'  dateRep in case file by to match with date in 
##'  \code{time_series_file}
##' 
##' @returns Data for use with particle filter
##' 
##' @export
##' @importFrom utils read.csv
generate_data <- function(death_data_file,
                          admissions_data_file,
                          itu_colname = "number_of_confirmed_covid_19_patients_in_hdu_itu_at_0800_total",
                          itu_ignore_dates = c("2020-03-15"),
                          first_data_date = "2020-03-01",
                          death_file_day_shift = 2,  #####SHIFT BY 1 day or 2?
                          country_name = "United_Kingdom") {
  
  # Read death data file, and manipulate. Select country only, 
  # and ensure dates match up
  death_data <- utils::read.csv(death_data_file, sep = ",")
  death_data$dateRep <- as.Date(death_data$dateRep, format="%d/%m/%Y") - death_file_day_shift
  death_data <- death_data[death_data$dateRep >= as.Date(first_data_date),]
  death_data <- death_data[death_data$countriesAndTerritories == country_name,]
  if (nrow(death_data) < 1) {
    stop("No case data matching country and date filtering criteria")
  }
  
  # Open a time series and format
  # these are by task XX on ncov-outputs
  admissions_data <- utils::read.csv(admissions_data_file)
  if (!(itu_colname %in% names(admissions_data))) {
    stop("itu_colname not found in time_series_file")
  } else {
    names(admissions_data)[names(admissions_data) == itu_colname] <- "itu"
  }
  admissions_data$date <- as.Date(admissions_data$date, format="%Y-%m-%d")
  admissions_data <- admissions_data[admissions_data$date >= as.Date(first_data_date),]
  if (nrow(admissions_data) < 1) {
    stop("No admissions data matching date filtering criteria")
  }
  
  # Merge mortality and admissions data, allowing NAs where there
  # is no overlap
  data <- merge(admissions_data, death_data, 
                by.x="date", by.y="dateRep",
                all.x=TRUE, all.y=TRUE)[,c("date", "deaths", "itu")]
  if (nrow(data) < 1 || 
      nrow(data) == nrow(admissions_data) + nrow(death_data) || 
      ncol(data) != 3) {
    stop("Merge of case and admissions data failed - do dates match?")
  }
  
  # Ignoring ITU on passed dates
  data[data$date == as.Date(itu_ignore_dates), "itu"] <- NA
  
  data
}

##' Create a model, and fit with the particle filter
##' 
##' @title Run particle filter
##' 
##' @param data to fit to, generated by 
##'   \code{data_from_deaths_admissions}
##'   
##' @param sircovid_model An sircovid model to use
##'  
##' @param model_params Parameters to run model simulations,
##'   generated by \code{generate_parameters()}
##'   
##' @param model_start_date Date to run model simulations from
##' 
##' @param obs_params List of parameters used for comparing
##'   model to data in the particle filter
##'   
##' @param n_particles Number of particles  
##' 
##' @param forecast_days Days ahead to include in output
##' 
##' @param save_particles Whether to save trajectories
##' 
##' @param return Set return depending on what is needed. 'full' gives
##'   the entire particle filter output, 'll' gives the
##'   log-likelihood, 'sample' gives a sampled particle's
##'   trace, 'single' gives the final state
##' 
##' @return Results from particle filter
##' 
##' @export
run_particle_filter <- function(data,
                                sircovid_model,
                                model_params,
                                model_start_date = "2020-02-02",
                                obs_params = list(phi_general = 0.95,
                                                  k_general = 2,
                                                  phi_ICU = 0.95,
                                                  k_ICU = 2,
                                                  phi_death = 1789/1651,
                                                  k_death = 2,
                                                  exp_noise = 1e6),
                                n_particles = 1000,
                                forecast_days = 0,
                                save_particles = FALSE,
                                return = "full") {
  # parameter checks
  if (!(return %in% c("full", "ll", "sample", "single"))) {
    stop("return argument must be full, ll, sample or single")
  }
  if (as.Date(data$date[1], "%Y-%m-%d") < as.Date(model_start_date, "%Y-%m-%d")) {
    stop("Model start date is later than data start date")
  }
  if (!save_particles && return == "sample") {
    message("Must save particles to sample runs")
    save_particles <- TRUE
  }
  if (save_particles && return == "single") {
    stop("Cannot save particles if only returning a single state")
  }
  
  if (return == "single") {
    save_sample_state <- TRUE
  } else {
    save_sample_state <- FALSE
  }

  #convert data into particle-filter form
  data <- particle_filter_data(data = data, 
                               start_date = model_start_date, 
                               steps_per_day = round(1 / model_params$dt)) 

  #set up model
  model_func <- sircovid_model$odin_model(user = model_params)
  
  #set up compare for observation likelihood
  compare_func <- sircovid_model$compare_model(model = model_func, pars_obs = obs_params, data = data)

  pf_results <- particle_filter(data = data, 
                                model = model_func,
                                compare = compare_func, 
                                n_particles = n_particles, 
                                save_particles = save_particles,
                                forecast_days = forecast_days,
                                save_sample_state = save_sample_state)  
  
  # Set return type
  # 'full' and 'single' are handled by particle_filter()
  # as long as the right parameters are given
  if (return == "ll") {
    ret <- pf_results$log_likelihood
  } else if (return == "sample") {
    ret <- pf_results$states[, ,sample(n_particles, 1)]
  } else if (return == "single" || return == "full") {
    ret <- pf_results
  }
  
  ret
}
