on:
  pull_request:
    branches:
      - master
      - main

name: Version Check

jobs:
  all:
    runs-on: ubuntu-20.04

    name: Version Check

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2.1.1

      - name: Check version format
        run: ./scripts/version_check
